### ISSUE TITLE
Ignoring changes in some files

### ISSUE THREAD

**Issue by madvas** [district0x/lein-solc#2]
When editing `RegistryEntry.sol` on MemeFactory, the plugin outputs: `Ignoring changes in resources/public/contracts/src/RegistryEntry.sol`. 
Which shouldn't be.

**Comment by fbielejec** [comment]
you should `add RegistryEntry` to the `:contracts` array to put it under watch.

**Comment by madvas** [comment]
I think more practical would be if it watched all files in the folder

**Comment by fbielejec** [comment]
Someone still might want to watch only some. I'll add the option to use either:

- `:contracts []` for an array of files
- `:contracts :all` (default) to watch all files
